version: "2.3"
services:
   sftp:
     build: ./ftp
     container_name: sftp
     ports:
         - "223:22"
     volumes:
       - ./ftp:/opt/data
     networks:
       - devops_network
     depends_on:
        python:
           condition: service_healthy
     healthcheck:
       test: ["CMD", "python", "ps.py"]
       interval: 3s
       timeout: 5s
       retries: 2
       start_period: 3s
     
   python:
     build: ./python 
     container_name: python
     volumes: 
       - ./python:/opt/data
       - ./python:/opt/app
     healthcheck:
       test: ["CMD", "python", "sql_orm.py"]
       interval: 3s
       timeout: 5s
       retries: 2
       start_period: 3s
    
   nginx:
     build: ./nginx
     container_name: nginx
     ports:
       - "80:883"
     volumes:
       - ./nginx:/opt/app
     depends_on:
       python:
         condition: service_healthy
     environment:
       - ENV=development
     healthcheck:
       test: ["CMD", "ls", "-lsa"]
       interval: 3s
       timeout: 2s
       retries: 5
       start_period: 1s

networks:
  devops_network:
    driver: bridge
