version: "2.3"
services:
   sftp:
     build: ./ftp
     container_name: sftp
     ports:
         - "223:22"
     volumes:
       - ./ftp:/opt/data
     networks:
       - devops_network
     
     healthcheck:
       test: ["CMD", "ls -la"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

   python:
     build: ./python 
     container_name: python
     volumes: 
       - ./python:/opt/data
       - ./python:/opt/app
     depends_on:
       sftp:
         condition: service_healthy
  
       healthcheck:
       test: ["CMD-SHELL", "ls", "-lsa"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

   nginx:
     build: ./nginx
     container_name: nginx
     ports:
       - "80:883"
     volumes:
       - ./nginx:/opt/app
     depends_on:
       python:
         condition: service_healthy
#      environment:
#        - ENV=development
#      healthcheck:
#        test: ["CMD-SHELL", "ls", "-lsa"]
#        interval: 3s
#        timeout: 5s
#        retries: 5
#        start_period: 1s

networks:
  devops_network:
    driver: bridge
