version: '2.3'

services:
  sftp:
    build: ./ftp
    volumes:
        - ./:/opt/data
    healthcheck:
       test:  ["CMD-SHELL", "test -f /logs/logfile.log"]
       interval: 3s
       timeout: 5s
       retries: 10
       start_period: 1s

#   sftp:
#     build: sftp
#     volumes:
#         - ./result:/home/foo/upload
#     ports:
#         - "223:22"
#     command: foo:pass:1001

  python:
    build: ./python
    volumes:
        - ./:/opt/data/
        - ./:/opt/app/
    healthcheck:
       test:  ["CMD-SHELL", "test -f /app/result/access_log_1.xlsx"]
       interval: 3s
       timeout: 5s
       retries: 10
       start_period: 1s

  nginx:
    build: nginx/
    ports:
        - "883:80"
    depends_on:
      python:
        condition: service_healthy
    volumes: 
       - ./html:/opt/app/
