version: "2.3"
services:
   sftp:
     build: ./ftp
     container_name: sftp
     ports:
         - "223:22"
     volumes:
       - ./ftp:/opt/data
       - ./ftp:/opt/app
     networks:
       - devops_network    
     
   python:
     build: ./python 
     container_name: python
     volumes: 
       - ./python:/opt/data
       - ./python:/opt/app
   
   nginx:
     build: ./nginx
     container_name: nginx
     ports:
       - "80:883"
     volumes:
       - ./nginx:/opt/app
      start_period: 1s

networks:
  devops_network:
    driver: bridge
